NAME = BitcoinExchange

CC = c++

CPPFLAGS = -Wall -Wextra -Werror -std=c++98

SRCS = main.cpp
OBJS = $(SRCS:.cpp=.o)

RM = rm -f

all : $(NAME)

$(NAME) :		$(OBJS)
						$(CC) $(CPPFLAGS) $(OBJS) -o $(NAME)

clean :
				$(RM) $(NAME)

re : fclean all